name: Build Swell Pipeline # Cron job to get swell data from API, load to Motherduck and publish to Streamlit

on:
  schedule:
    - cron: "0 22 * * *"  # UTC +11 Sydney Time (9am)
  workflow_dispatch:       # Manual triggering from Github UI

jobs:
  setup_vm:
    runs-on: ubuntu-latest

    steps:

      - name: Set Timezone
        run: sudo timedatectl set-timezone "Australia/Sydney"
        
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

  run_scripts:
    needs: setup_vm
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Get swell data
        run: python get_swell_data.py

        - name: Load data to Motherduck & build tables / views
          env:
            MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}
          run: python load_data.py


